

version: '3'
services:
    nginx:
      image: nginx:stable-alpine
      container_name: nginx
      ports:
        - "80:80"
      volumes:
        - ./:/var/www/html
        - ./docker/config/app.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
    php:
        build:
          context: .
          dockerfile: ./docker/Dockerfile
        restart: always
        container_name: php
        volumes:
            - "./:/var/www/html"
        ports:
          - "9000:9000"
    mysql:
        image: mysql:5.6
        container_name: mysql
        ports:
          - "3306:3306"
        volumes:
          - ./docker/mysql:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: password  
      
    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
